### PR TITLE
Update docker machine 0.5.0

### PR DESCRIPTION
**Pull request by StefanScherer**
It now downloads the ZIP file and shimgen's all the exe files automatically. Tested it with `docker-machine create -d digitalocean --digitalocean-access-token mytoken do` and worked fine.

### CODE REVIEW

**Comment by StefanScherer** [comment]
After you have pushed it to Chocolatey I'll ask Rob Reynolds to moderate all the waiting versions to have all the docker tools up-to-date.

**Comment by StefanScherer** [comment]
@silarsis I kindly can offer you help keeping this chocolatey package up-to-date and also can help push that to chocolatey.org. So if you like I could collaborate and push future packages or even take over the maintenance. Just let me know.

**Comment by silarsis** [comment]
Never turn down assistance - that'd be great, thanks. I've added you as a contributor - let me know if that provides you enough access or not, I've not actually shared write access to a github repo before outside of setting up an org and teams...

**Comment by StefanScherer** [comment]
Thanks. Yes a contributor can push to GitHub. I think at Chocolatey there also might be some menu item to add maintainers to push the package. If you push the package let me know to get itmoderatedsoon.

**Comment by StefanScherer** [comment]
@silarsis Thanks for adding me as a moderator at Chocolatey. I've updated the nuspec file with more project links and then pushed it to chocolatey. We now have a fast track to get this moderated very quickly ;-)

I also updated the MAINTENANCE.md to use `choco push`.

**Pull request merged**
